### ISSUE TITLE
Fallo al realizar el recuento de votos

### ISSUE THREAD

**Issue by CarlosW4E** [decide-europa/decide-europa#1]
Creo una votación, empieza la votación, se cierra y a la hora de hacer el recuento aparece un fallo.
El fallo aparece tanto en local como en producción con docker.
El fallo aparece cuando hay votos para contar, así como cuando no se ha llevado a cabo la votación aún.
La traza del fallo es la siguiente: http://dpaste.com/3FV3V8E

Resumen: 

Request Method: | POST
-- | --
http://localhost:8000/admin/voting/voting/
2.0
TypeError
string indices must be integers
/home/carlos/Escritorio/workspace/decide-europa-cabina/decide/voting/models.py in <listcomp>, line 64
/usr/bin/python3
3.6.7
['/home/carlos/Escritorio/workspace/decide-europa-cabina/decide',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/home/carlos/.local/lib/python3.6/site-packages',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Mon, 26 Nov 2018 18:34:25 +0000

**Comment by Pacoliva** [comment]
Se escala la incidencia al repositorio específico del módulo.

**Comment by Avilocap** [comment]
Esta issue se ha descartado porque no va a ser una de las prioridades del equipo de mixnet durante el desarrollo. Se cierra.
