### ISSUE TITLE
Petición a autenticación

### ISSUE THREAD

**Issue by Avilocap** [decide-europa/decide-europa#14]
Desde el módulo de Mixnet, no gustaría que todas las urls que están en decide/mixnet/urls.py solo pudieran ser accesibles por usuarios autentificados en el sistema.

**Comment by Serferjim** [comment]
Paso a crear una Issue en el repositorio de autenticación para implementar dicho cambio.

**Comment by Serferjim** [comment]
Debido a problemas de integración con otros submódulos esta Issue no será resuelta.
