### ISSUE TITLE
Implementación de ElGamal para la aplicación de escritorio de cabina.

### ISSUE THREAD

**Issue by CarlosW4E** [decide-europa/decide-europa#15]
¿Qué se quiere hacer?: Necesitamos implementar ElGamal en el código de la vista de votación para poder enviar la respuesta a Decide.
¿Por qué se quiere hacer?: Porque de lo contrario no se puede llevar a cabo la votación o se tendría que mandar sin cifrar a Decide.
Módulos afectados: Mixnet, Cabina.
Cómo se ven afectados: necesitamos que se implemente en la aplicación el cifrado.

**Comment by CarlosW4E** [comment]
@Avilocap  Ya hemos añadido el pull request para que podáis resolver la issue #17.

**Comment by CarlosW4E** [comment]
El código para resolver esta issue se encuentra en el pull request #17

**Comment by Avilocap** [comment]
Se ha implementado los solicitado en el commit 7b36806bf2012759d5d68bfd62125f86de45a4b7

**Comment by CarlosW4E** [comment]
Ya está la rama lista para revisar los cambios de la aplicación de escritorio.
La rama es: [https://github.com/decide-europa/decide-europa/tree/decide-cabina-escritorio](decide-cabina-escritorio)
Para saber más detalles acerca de como iniciar la aplicación mirad el README.md que está en el pull request #17

**Comment by manmacbec** [comment]
Se ha comprobado el funcionamiento y parece funcionar todo según lo esperado

**Comment by juandelaoliva** [comment]
Comprobado y sin errores. Funciona como es previsto.

**Comment by CarlosW4E** [comment]
Procedo a realizar el merge, ya que ha sido revisado por dos coordinadores.
